on:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write

name: Release Generator

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/create-github-app-token@5d869da34e18e7287c1daad50e0b8ea0f506ce69 # v1.11.0
        id: sre_app_token
        with:
          app_id: ${{ secrets.SRE_BOT_RW_APP_ID }}
          private_key: ${{ secrets.SRE_BOT_RW_PRIVATE_KEY }}

      - uses: google-github-actions/release-please-action@e4dc86ba9405554aeba3c6bb2d169500e7d3b4ee # v4.1.1
        with:
          token: ${{ steps.sre_app_token.outputs.token }}
